# Generated by Django 3.1 on 2020-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerobot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
