# Generated by Django 3.1 on 2020-09-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerobot', '0004_auto_20200902_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsers',
            name='link',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
