# Generated by Django 3.1 on 2020-09-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerobot', '0005_auto_20200902_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsers',
            name='name',
        ),
    ]
