# Generated by Django 3.1 on 2020-09-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerobot', '0006_remove_sponsers_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gllery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'Gllery',
                'verbose_name_plural': 'Gllery',
            },
        ),
        migrations.AddField(
            model_name='sponsers',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
