# Generated by Django 3.1 on 2020-09-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerobot', '0007_auto_20200902_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gllery',
            new_name='Gallery',
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
