# Generated by Django 3.1 on 2020-09-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerobot', '0008_auto_20200902_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsers',
        ),
    ]
