# Generated by Django 3.1 on 2020-09-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerobot', '0011_auto_20200902_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
