# Generated by Django 3.1 on 2020-09-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerobot', '0012_gallery_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='link',
        ),
    ]
